export const LOGIN_EMAIL_CHANGE = 'LOGIN_EMAIL_CHANGE';
export const LOGIN_PASSWORD_CHANGE = 'LOGIN_PASSWORD_CHANGE';
export const LOGIN_REQUEST_LOGIN = 'LOGIN_REQUEST_LOGIN';
export const LOGIN_REQUEST_LOGIN_SUCCESS = 'LOGIN_REQUEST_LOGIN_SUCCESS';
