export const REGISTER_USER_EMAIL_CHANGE = 'REGISTER_USER_EMAIL_CHANGE';
export const REGISTER_USER_PASSWORD_CHANGE = 'REGISTER_USER_PASSWORD_CHANGE';
export const REGISTER_USER_VERIFIED_PASSWORD_CHANGE = 'REGISTER_USER_VERIFIED_PASSWORD_CHANGE';
export const REGISTER_VERIFY_PASSWORD_SUCCESS = 'REGISTER_VERIFY_PASSWORD_SUCCESS';
export const REGISTER_VERIFY_PASSWORD_ERROR = 'REGISTER_VERIFY_PASSWORD_ERROR';
export const REGISTER_USER_REQUEST_ACCOUNT_CREATE = 'REGISTER_USER_REQUEST_ACCOUNT_CREATE';
export const REGISTER_USER_REQUEST_SUCCESS = 'REGISTER_USER_REQUEST_SUCCESS';

