export const NEW_CHALLENGE_UPDATE_NAME = 'NEW_CHALLENGE_UPDATE_NAME';
export const NEW_CHALLENGE_UPDATE_START_DATE = 'NEW_CHALLENGE_UPDATE_START_DATE';
export const NEW_CHALLENGE_UPDATE_END_DATE = 'NEW_CHALLENGE_UPDATE_END_DATE';
export const NEW_CHALLENGE_SET_REQUEST = "NEW_CHALLENGE_SET_REQUEST";