export const REGISTER_USER_EMAIL_CHANGE = 'REGISTER_USER_EMAIL_CHANGE';
export const REGISTER_USER_PASSWORD_CHANGE = 'REGISTER_USER_PASSWORD_CHANGE';
export const REGISTER_USER_VERIFIED_PASSWORD_CHANGE = 'REGISTER_USER_VERIFIED_PASSWORD_CHANGE';
export const REGISTER_VERIFY_USER_PASSWORD = 'REGISTER_VERIFY_USER_PASSWORD';
